networks:
  public:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true
  private:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true
#  rabbitmq_net:
#    driver: overlay

volumes:
  db-data:

services:
  database:
    image: postgres:9.6.6
    networks:
      - private
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
  #          update_config:
  #              order: 'stop-first'
  #          rollback_config:
  #              order: 'stop-first'
  #          resources:
  #              limits:
  #                cpus: '1.00'
  #                memory: 50M
  #              reservations:
  #                cpus: '0.25'
  #                memory: 50M
  backend:
    image: rodoch/back-end-image:latest
    volumes:
      - /var/log/start-app/backend:/var/log
    networks:
      - private
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'postgres'
    depends_on:
      - database
    deploy:
      replicas: 1
  #          restart_policy:
  #            condition: on-failure
  #            max_attempts: 10
  #            delay: 5s
  #          update_config:
  #            parallelism: 1
  #            delay: 5s
  #          resources:
  #              limits:
  #                cpus: '0.50'
  #                memory: 15M
  #              reservations:
  #                cpus: '0.25'
  #                memory: 15M
  consumer:
    image: rodoch/consumer-service-image:latest
    volumes:
      - /var/log/start-app/consumer-service:/var/log
    networks:
      - private
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'postgres'
    depends_on:
      - database
    deploy:
      replicas: 1
  frontend:
    image: rodoch/front-end-image:latest
    networks:
      - public
      - private
    volumes:
      - /var/log/start-app/frontend:/var/log
    ports:
      - '5000:5000'
    deploy:
      replicas: 1

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=duJLSnUj3nia1n5GZIse6A==
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - private
#    healthcheck:
#      test: [ "CMD", "rabbitmqctl", "status" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5