services:
 backend:
  image: back-end-image:latest
  volumes:
   - /var/log/start-app/backend:/var/log
  deploy:
   replicas: 1
 frontend:
  image: front-end-image:latest
  volumes:
   - /var/log/start-app/frontend:/var/log
  ports:
   - "5000:5000"
  deploy:
   replicas: 1

