CREATE SCHEMA IF NOT EXISTS START_APP;

--CREATE TABLE IF NOT EXISTS START_APP.customer (
--id SERIAL PRIMARY KEY,
--firstname VARCHAR(100) NOT NULL,
--lastname VARCHAR(255) NOT NULL
--);

CREATE TABLE IF NOT EXISTS START_APP.book (
  isbn SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP WITHOUT TIME ZONE,
  modifiedAt TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS author (
  isbn SERIAL NOT NULL,
  author VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (isbn) REFERENCES START_APP.BOOK(isbn)
);