CREATE SCHEMA IF NOT EXISTS start_app;


CREATE TABLE IF NOT EXISTS start_app.book (
  isbn SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  modified_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS start_app.author (
  isbn SERIAL NOT NULL,
  author VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (isbn) REFERENCES start_app.book(isbn)
);