CREATE SCHEMA IF NOT EXISTS START_APP;
--DROP TABLE IF EXISTS START_APP.customer;
CREATE TABLE IF NOT EXISTS START_APP.customer (
id SERIAL PRIMARY KEY,
firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(255) NOT NULL
);