networks:
  rabbitmq_net:
    driver: bridge

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=duJLSnUj3nia1n5GZIse6A==
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  rabbitmq2:
#    image: rabbitmq:3-management
#    hostname: rabbitmq2
#    environment:
#      - RABBITMQ_ERLANG_COOKIE=duJLSnUj3nia1n5GZIse6A==
#    depends_on:
#      rabbitmq1:
#        condition: service_healthy
#    networks:
#      - rabbitmq_net
#    command: rabbitmqctl join_cluster rabbit@rabbitmq1
#
#  rabbitmq3:
#    image: rabbitmq:3-management
#    hostname: rabbitmq3
#    environment:
#      - RABBITMQ_ERLANG_COOKIE=HwTrwWCJoffkJb78T7d2IA==
#    depends_on:
#      rabbitmq1:
#        condition: service_healthy
#    networks:
#      - rabbitmq_net
#    command: rabbitmqctl join_cluster rabbit@rabbitmq1
