services:
  rabbitmq1:
    build: .
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE=SHARED_SECRET_COOKIE
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - rabbitmq_net
  rabbitmq2:
    build: .
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=SHARED_SECRET_COOKIE
      - RABBITMQ_CLUSTER_NODE=rabbit1
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net: